name: Build and Release Tetrix

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found — skipping pip install"
            exit 1
          fi
        shell: bash

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt } else { Write-Host 'No requirements.txt found — skipping pip install'; exit 1 }
        shell: pwsh

      - name: Build on Windows
        if: runner.os == 'Windows'
        run: .\build_windows.ps1
        shell: pwsh

      - name: Build on Linux
        if: runner.os == 'Linux'
        run: |
          chmod +x ./build_unix.sh || true
          bash ./build_unix.sh
        shell: bash

      - name: Build on macOS
        if: runner.os == 'macOS'
        run: |
          chmod +x ./build_unix.sh || true
          bash ./build_unix.sh
        shell: bash

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tetrix-${{ matrix.os }}
          path: dist/**

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download linux artifact
        uses: actions/download-artifact@v4
        with:
          name: tetrix-ubuntu-latest
          path: artifacts/ubuntu

      - name: Download windows artifact
        uses: actions/download-artifact@v4
        with:
          name: tetrix-windows-latest
          path: artifacts/windows

      - name: Download macos artifact
        uses: actions/download-artifact@v4
        with:
          name: tetrix-macos-latest
          path: artifacts/macos

      - name: Generate checksums
        run: |
          mkdir -p artifacts/checksums
          find artifacts -type f -not -path "artifacts/checksums/*" -exec sha256sum {} \; > artifacts/checksums/checksums.sha256 || true
        shell: bash

      - name: "Debug: list downloaded artifacts"
        run: |
          echo "Listing artifacts directory"
          ls -la artifacts || true
          echo "Recursive listing"
          find artifacts -maxdepth 4 -type f -print -exec du -h {} \; || true
        shell: bash

      - name: "Create draft release"
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: |
            Release automática generada por GitHub Actions for tag ${{ github.ref_name }}.
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Package artifacts into tar.gz"
        run: |
          set -euo pipefail
          mkdir -p artifacts_zips
          # Create a single tarball with everything under artifacts/
          if [ -d artifacts ]; then
            tar -czf artifacts_zips/tetrix-artifacts.tar.gz -C artifacts .
          else
            echo "No artifacts directory found; nothing to package"
            exit 1
          fi
          ls -la artifacts_zips
        shell: bash

      - name: "Upload packaged artifacts to draft release"
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts_zips/tetrix-artifacts.tar.gz
          asset_name: tetrix-artifacts-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip
